config/routes.rb
Idac::Application.routes.draw do

  devise_for :users

  resources :users do
    resources :tester_answers
  end

  resources :questions

  resources :testers

  root :to => 'pages#index'
  

end

app/models/tester_answer.rb
# == Schema Information
#
# Table name: tester_answers
#
#  id         :integer          not null, primary key
#  answer     :text
#  score      :integer
#  ability    :integer
#  std_error  :integer
#  tester_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class TesterAnswer < ActiveRecord::Base
  attr_accessible :ability, :answer, :score, :std_error, :user_id

  belongs_to :user
  validates :user_id, presence: :true
end

app/controllers/tester_answers_controller.rb
class TesterAnswersController < ApplicationController
  # GET /tester_answers
  # GET /tester_answers.json
  def index
    @tester_answers = current_user.tester_answers.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tester_answers }
    end
  end

  # GET /tester_answers/1
  # GET /tester_answers/1.json
  def show
    @tester_answer = current_user.tester_answers.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tester_answer }
    end
  end

  # GET /tester_answers/new
  # GET /tester_answers/new.json
  def new
    @tester_answer = current_user.tester_answers.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tester_answer }
    end
  end

  # GET /tester_answers/1/edit
  def edit
    @tester_answer = current_user.tester_answers.find(params[:id])
  end

  # POST /tester_answers
  # POST /tester_answers.json
  def create
    @tester_answer = current_user.tester_answers.new(params[:tester_answer])

    respond_to do |format|
      if @tester_answer.save
        format.html { redirect_to @tester_answer, notice: 'Tester answer was successfully created.' }
        format.json { render json: @tester_answer, status: :created, location: @tester_answer }
      else
        format.html { render action: "new" }
        format.json { render json: @tester_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tester_answers/1
  # PUT /tester_answers/1.json
  def update
    @tester_answer = current_user.tester_answers.find(params[:id])

    @tester_answer.update_attributes(params[:tester_answer])
    redirect_to root_path

  end

  # DELETE /tester_answers/1
  # DELETE /tester_answers/1.json
  def destroy
    @tester_answer = current_user.tester_answers.find(params[:id])
    @tester_answer.destroy

    respond_to do |format|
      format.html { redirect_to tester_answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tester_answers_helper.rb
module TesterAnswersHelper
end

app/views/tester_answers/_form.html.erb
<%= form_for(@tester_answer) do |f| %>
  <% if @tester_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tester_answer.errors.count, "error") %> prohibited this tester_answer from being saved:</h2>

      <ul>
      <% @tester_answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :ability %><br />
    <%= f.number_field :ability %>
  </div>
  <div class="field">
    <%= f.label :std_error %><br />
    <%= f.number_field :std_error %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tester_answers/edit.html.erb
<h1>Editing tester_answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @tester_answer %> |
<%= link_to 'Back', tester_answers_path %>

app/views/tester_answers/index.html.erb
<h3><%= current_user.name %> 測驗結果</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>回答</th>
      <th>分數</th>
      <th>能力估計</th>
      <th>標準誤</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
    
  <tbody>

    <% @tester_answers.each do |tester_answer| %>
      <tr>
        <td><%= tester_answer.answer %></td>
        <td><%= tester_answer.score %></td>
        <td><%= tester_answer.ability %></td>
        <td><%= tester_answer.std_error %></td>
        <td><%= link_to 'Show', [current_user, tester_answer] %></td>
        <td><%= link_to 'Edit', edit_user_tester_answer_path(current_user, tester_answer) %></td>
        <td><%= link_to 'Destroy', [current_user, tester_answer], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>

</table>

app/views/tester_answers/new.html.erb
<h1>New tester_answer</h1>

<%= render 'form' %>

<%= link_to 'Back', tester_answers_path %>

app/views/tester_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Answer:</b>
  <%= @tester_answer.answer %>
</p>

<p>
  <b>Score:</b>
  <%= @tester_answer.score %>
</p>

<p>
  <b>Ability:</b>
  <%= @tester_answer.ability %>
</p>

<p>
  <b>Std error:</b>
  <%= @tester_answer.std_error %>
</p>