config/routes.rb
Idac::Application.routes.draw do

  devise_for :users

  resources :users do
    resources :tester_answers
  end

  resources :questions

  resources :testers

  root :to => 'pages#index'
  

end

app/models/tester.rb
# == Schema Information
#
# Table name: testers
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  total_score :integer
#  test_date   :datetime
#  birthday    :datetime
#  sub_score_1 :integer
#  sub_score_2 :integer
#  sub_score_3 :integer
#  sub_score_4 :integer
#  sub_score_5 :integer
#  sub_score_6 :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  dob         :date
#

class Tester < ActiveRecord::Base
  attr_accessible :birthday, :dob, :name, :sub_score_1, :sub_score_2, :sub_score_3, :sub_score_4, :sub_score_5, :sub_score_6, :test_date, :total_score

  has_many :tester_answers, dependent: :destroy

end

app/controllers/testers_controller.rb
class TestersController < ApplicationController
  # GET /testers
  # GET /testers.json
  def index
    @testers = Tester.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @testers }
    end
  end

  # GET /testers/1
  # GET /testers/1.json
  def show
    @tester = Tester.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tester }
    end
  end

  # GET /testers/new
  # GET /testers/new.json
  def new
    @tester = Tester.new

    respond_to do |format|
      format.html { redirect_to root_path}
    end

  end

  # GET /testers/1/edit
  def edit
    @tester = Tester.find(params[:id])
  end

  # POST /testers
  # POST /testers.json
  def create
    @tester = Tester.new(params[:tester])

    respond_to do |format|
      format.html { redirect_to root_path}
    end
  end

  # PUT /testers/1
  # PUT /testers/1.json
  def update
    @tester = Tester.find(params[:id])

    respond_to do |format|
      if @tester.update_attributes(params[:tester])
        format.html { redirect_to @tester, notice: 'Tester was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testers/1
  # DELETE /testers/1.json
  def destroy
    @tester = Tester.find(params[:id])
    @tester.destroy

    respond_to do |format|
      format.html { redirect_to testers_url }
      format.json { head :no_content }
    end
  end

  
end

app/helpers/testers_helper.rb
module TestersHelper
end

app/views/testers/_form.html.erb
<%= form_for(@tester) do |f| %>
  <% if @tester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tester.errors.count, "error") %> prohibited this tester from being saved:</h2>

      <ul>
      <% @tester.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :total_score %><br />
    <%= f.number_field :total_score %>
  </div>
  <div class="field">
    <%= f.label :test_date %><br />
    <%= f.datetime_select :test_date %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.datetime_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :sub_score_1 %><br />
    <%= f.number_field :sub_score_1 %>
  </div>
  <div class="field">
    <%= f.label :sub_score_2 %><br />
    <%= f.number_field :sub_score_2 %>
  </div>
  <div class="field">
    <%= f.label :sub_score_3 %><br />
    <%= f.number_field :sub_score_3 %>
  </div>
  <div class="field">
    <%= f.label :sub_score_4 %><br />
    <%= f.text_field :sub_score_4 %>
  </div>
  <div class="field">
    <%= f.label :sub_score_5 %><br />
    <%= f.number_field :sub_score_5 %>
  </div>
  <div class="field">
    <%= f.label :sub_score_6 %><br />
    <%= f.number_field :sub_score_6 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/testers/_new_tester_form.html.erb
<% @tester = Tester.new %>
<% current_year = Date.current.year %>

<%= form_for(@tester) do |f| %>
  <% if @tester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tester.errors.count, "error") %> prohibited this tester from being saved:</h2>

      <ul>
      <% @tester.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "測試者姓名" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :test_date, "設定測試日期" %><br />
    <%= f.date_select :test_date, :start_year => 2014 %>
  </div>
  <div class="field">
    <%= f.label :dob, "設定生日" %><br />
    <%= f.date_select :dob, :start_year => (current_year-10), :end_year => (current_year-3) %>
  </div>
  <div class="actions">
    <%= f.submit "設立新的測試", class: "btn btn-min btn-warning" %>
  </div>
<% end %>

app/views/testers/edit.html.erb
<h1>Editing tester</h1>

<%= render 'form' %>

<%= link_to 'Show', @tester %> |
<%= link_to 'Back', testers_path %>

app/views/testers/index.html.erb
<h1>Listing testers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Total score</th>
    <th>Test date</th>
    <th>Birthday</th>
    <th>Sub score 1</th>
    <th>Sub score 2</th>
    <th>Sub score 3</th>
    <th>Sub score 4</th>
    <th>Sub score 5</th>
    <th>Sub score 6</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @testers.each do |tester| %>
  <tr>
    <td><%= tester.name %></td>
    <td><%= tester.total_score %></td>
    <td><%= tester.test_date %></td>
    <td><%= tester.birthday %></td>
    <td><%= tester.sub_score_1 %></td>
    <td><%= tester.sub_score_2 %></td>
    <td><%= tester.sub_score_3 %></td>
    <td><%= tester.sub_score_4 %></td>
    <td><%= tester.sub_score_5 %></td>
    <td><%= tester.sub_score_6 %></td>
    <td><%= link_to 'Show', tester %></td>
    <td><%= link_to 'Edit', edit_tester_path(tester) %></td>
    <td><%= link_to 'Destroy', tester, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tester', new_tester_path %>

app/views/testers/new.html.erb
<h1>New tester</h1>

<%= render 'form' %>

<%= link_to 'Back', testers_path %>

app/views/testers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tester.name %>
</p>

<p>
  <b>Total score:</b>
  <%= @tester.total_score %>
</p>

<p>
  <b>Test date:</b>
  <%= @tester.test_date %>
</p>

<p>
  <b>Birthday:</b>
  <%= @tester.birthday %>
</p>

<p>
  <b>Sub score 1:</b>
  <%= @tester.sub_score_1 %>
</p>

<p>
  <b>Sub score 2:</b>
  <%= @tester.sub_score_2 %>
</p>

<p>
  <b>Sub score 3:</b>
  <%= @tester.sub_score_3 %>
</p>

<p>
  <b>Sub score 4:</b>
  <%= @tester.sub_score_4 %>
</p>

<p>
  <b>Sub score 5:</b>
  <%= @tester.sub_score_5 %>
</p>

<p>
  <b>Sub score 6:</b>
  <%= @tester.sub_score_6 %>
</p>


<%= link_to 'Edit', edit_tester_path(@tester) %> |
<%= link_to 'Back', testers_path %>